// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV9UoNsdRCLLz1HWgdmRbZqsYwvsRBH6A',
    appId: '1:426821749244:web:a9a9a2a0e18c9ff74cca79',
    messagingSenderId: '426821749244',
    projectId: 'spotify-clone-96e21',
    authDomain: 'spotify-clone-96e21.firebaseapp.com',
    storageBucket: 'spotify-clone-96e21.appspot.com',
    measurementId: 'G-K0E2FF89FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiccfAlOXTV_Ebgl1JlA9NBaTuvGxVtz4',
    appId: '1:426821749244:android:afaa19648ddc9cc24cca79',
    messagingSenderId: '426821749244',
    projectId: 'spotify-clone-96e21',
    storageBucket: 'spotify-clone-96e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE0uv1WAEZIzAbBvCVYd47QvCB6gAETN8',
    appId: '1:426821749244:ios:936be28027bdae674cca79',
    messagingSenderId: '426821749244',
    projectId: 'spotify-clone-96e21',
    storageBucket: 'spotify-clone-96e21.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE0uv1WAEZIzAbBvCVYd47QvCB6gAETN8',
    appId: '1:426821749244:ios:936be28027bdae674cca79',
    messagingSenderId: '426821749244',
    projectId: 'spotify-clone-96e21',
    storageBucket: 'spotify-clone-96e21.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV9UoNsdRCLLz1HWgdmRbZqsYwvsRBH6A',
    appId: '1:426821749244:web:00b0ddbea01d4f684cca79',
    messagingSenderId: '426821749244',
    projectId: 'spotify-clone-96e21',
    authDomain: 'spotify-clone-96e21.firebaseapp.com',
    storageBucket: 'spotify-clone-96e21.appspot.com',
    measurementId: 'G-NR0VS7BH8B',
  );
}
